apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deployment
  namespace: cars
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
